### PR TITLE
W.I.P: feat: Customise interval duration inside dropdown

### PR DESCRIPTION
**Pull request by mittalyashu**
Here's a preview of the implementation.

| Preview |
| --- |
| CleanShot 2024-03-20 at 18 58 26@2x | 

**Features**

* Based on the URL it is active on (Amazon, Reddit or Medium) only that button will be enable. Rest will be automatically be disabled.

**Notes**

* As Reddit released their new UI design, the current logic will only work on [older Reddit design](https://new.reddit.com/) (Year: 2018 - 2023)

/claim https://github.com/serpcompany/public/issues/1

### CODE REVIEW

**Comment by mittalyashu** [comment]
I am almost done.

@devinschumacher I am not able to find the logic for stopping the execution of the script in the codebase.

**Comment by mittalyashu** [comment]
> since theres no loom video i cant tel all the functionality

I am still polishing few things out. After that I share a loom video.

> is the GUI able to set all the different speeds and intervals in the task?

As I have shared in the screenshot preview. There is only 1 global speed input field for controlling the flow.

> i think theres 3 for medium and 2 for reddit.

Were you planning for have 3 different timer fields for medium and 2 timer fields for Reddit.
While that is feasible wouldn't that be too confusing for that end user.

**Comment by devinschumacher** [comment]
> Were you planning for have 3 different timer fields for medium and 2 timer fields for Reddit?


What is mean is this:

## Medium: 

The three areas that can take user customized settings for speed for medium are:

- [ ] await new Promise(resolve => setTimeout(resolve, randomDelay(100, 400))); // Random delay between 50ms and 200ms
- [ ] await new Promise(resolve => setTimeout(resolve, randomDelay(500, 1500))); // Wait 0.5 to 1 second before next button
- [ ] await new Promise(resolve => setTimeout(resolve, 3000)); // Wait for 3 seconds


1. the time between "claps" (you can do 50 claps on a single article)
2. the time between when the script finishes all claps on one article, and pauses before moving to the next clap icon on the page (like on a category page)
3. the time the script will wait to try to scroll down again to continue to load the infinite scroll page when it reaches the bottom 

@mittalyashu

**Comment by devinschumacher** [comment]
@mittalyashu can you shoot a quick LOOM so i can just look at the project working instead of having to open the code and review it all? will be faster for both of us!

**Comment by mittalyashu** [comment]
@devinschumacher

Loom video: https://www.loom.com/share/135edbea38f44c3c8e7b51b32a4c48c2?sid=3c8c1dbc-f1e2-4e12-8f14-2a125dbd7e0f

**Comment by devinschumacher** [comment]
@mittalyashu if youre interested - https://github.com/serpcompany/public/issues/14

**Pull request merged**
