### PR TITLE
feat: seeRobots feature

### PR DESCRIPTION
**Pull request by mittalyashu**
This PR adds SeeRobots feature to extension.

**Notes**

* According to OG extension, even if the page doesn't have the robots meta tag it shows the state in green color (I have explained about this in Loom video as well)

**Video**

https://www.loom.com/share/9276225baeaf46bcb6707e3623d52fdb?sid=470b038b-21c5-465e-993c-c8b356c54190

### CODE REVIEW

**Comment by devinschumacher** [comment]
@mittalyashu thats correct. it is the default state when nothing is defined

**Comment by devinschumacher** [comment]
@mittalyashu one correction - the feature should always be ON by default. should not have to click button to enable it. 

and we should make sure the "icon" in the chrome bar is colored accordingly.

**Comment by devinschumacher** [comment]
https://www.loom.com/share/c3db369a264f4f838febb9d4370fea24?from_recorder=1&focus_title=1

**Comment by mittalyashu** [comment]
> the feature should always be ON by default. should not have to click button to enable it.

I will update it.

> and we should make sure the "icon" in the chrome bar is colored accordingly.

Can you share the icon in Slack? I tried downloading it from https://github.com/serpcompany/serp-extension/issues/22, but the icon link seems to be private. 🤷🏻

**Comment by mittalyashu** [comment]
Update on running the feature in background while updating the icon

https://www.loom.com/share/ec8a204878764504b0330a1ca2b886fb?sid=494d221a-85fb-4830-bb66-4f3ad5a75b17

**Comment by devinschumacher** [comment]
@mittalyashu yeah thats the right idea but i was hoping to do this with our logo. see original issue - https://github.com/serpcompany/serp-extension/issues/22#:~:text=change%20the%20extension%20icon%20to%20the%20white%20serp%20logo%20(so%20we%20can%20change%20its%20colors%20like%20the%20%27see%20robots%27%20extension%20does)%20%2D%2D%20file%20below

**Comment by mittalyashu** [comment]
> @mittalyashu yeah thats the right idea but i was hoping to do this with our logo. see original issue - #22

Updated the icons

**Review by devinschumacher — APPROVED** [review]

**Pull request merged**
